name: Sonarless Code Scan
on:
  workflow_dispatch:
  push:
    branches:
      - master # or the name of your main branch
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: scan
        uses: gitricko/sonarless@v1.1
            
